### ISSUE TITLE
CarnivalCordovaPlugin.m - line 63

### ISSUE THREAD

**Issue by danielcherubini** [carnivalmobile/carnival-sdk-cordova#1]
```
dispatch_async(dispatch_get_main_queue(), ^{ // Make sure we're on the main thread for UIKit interactions - otherwise we'll crash. Cordova is calling these on a background thread for some reason.
    [self.webView stringByEvaluatingJavaScriptFromString:JSString];
});
```

---

No visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'

**Comment by samjarman** [comment]
Very strange, as `webView` is a property on the parent class, CDVPlugin which is a UIWebView, which of course declares `stringByEvaluatingJavaScriptFromString`.

@danmademe can you give me a bit more information about how you're building this? I know there are a LOT of tools out there for Cordova. I'll try replicate here.

**Comment by danielcherubini** [comment]
Pull request up https://github.com/carnivalmobile/carnival-sdk-cordova/pull/2

**Comment by danielcherubini** [comment]
basically the `stringByEvaulatingJavaScriptFromString` was deprecated in cordova-ios 4+ its now `evaluateJavaScript:completionHandler`
